service: pdf-serverless

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  deploymentBucket: projectx-lambda-upload

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - 'application/pdf'
      - 'image/png'

functions:
  pdfHandler:
    handler: app.pdfHandler
    events:
      - http: GET /pdf
        contentHandling: CONVERT_TO_BINARY
  pngHandler:
    handler: app.pngHandler
    events:
      - http: GET /png
        contentHandling: CONVERT_TO_BINARY