service: pdf-serverless

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - 'application/pdf'

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
        contentHandling: CONVERT_TO_BINARY
      - http: 'ANY {proxy+}'
        contentHandling: CONVERT_TO_BINARY